In [ ]:
#x[m][n]
#where
#x-->array name 
#m---row
#n---column

In [9]:
import numpy as np
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
print(x)
type(x)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


numpy.ndarray

In [12]:
import numpy as np
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]],dtype=complex)
print(x)

[[10.+0.j 20.+0.j 30.+0.j]
 [40.+0.j 50.+0.j 60.+0.j]
 [70.+0.j 80.+0.j 90.+0.j]]


In [14]:
#zero() and Ones
y=np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
y=np.ones((3,2))
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
z= np.ones((3,3),dtype=[('m','int'),('n','float')])
print(z)

[[(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]]


In [22]:
import numpy as np
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
#print(x)
for i in x: #this is for traverse use nestedloop
    for j in i:
        print(j,end=" ")
    print() #for new line


10 20 30 
40 50 60 
70 80 90 


In [26]:
import numpy as np
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
print("row 0:",x[0])
print("row 0:",x[1])

row 0: [10 20 30]
row 0: [40 50 60]


In [27]:
print(x[0:2])

[[10 20 30]
 [40 50 60]]


In [29]:
print(x[1:])

[[40 50 60]
 [70 80 90]]


In [30]:
print(x[::-1])

[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [31]:
#column tasks
print(x[: , 0])

[10 40 70]


In [48]:
print(x[0:2])
print(x[:0:-1])  #task

[[10 20 30]
 [40 50 60]]
[[70 80 90]
 [40 50 60]]


In [49]:
print(x[: , 0])

[10 40 70]


In [52]:
#Colunm representation
print("column 0:",x[:, 0])
print("column 1:",x[:, 1])
print("column 2:",x[:, 2])

column 0: [10 40 70]
column 1: [20 50 80]
column 2: [30 60 90]


In [4]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,20,30],[40,50,60],[70,80,90]])
result=[]
for i in range(len(arr1)):
    row=[]
    for j in range(len(arr1[0])):
         row.append(arr1[i,j]+arr2[i,j])
    result.append(row)
print(result)

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]
