In [2]:
import numpy as np
arr1=np.array([
    [1,2,3],[4,5,6]])
print("orginal array:")
print(arr1)
result=np.transpose(arr1)
print("Transpoe array:")
print(result)

orginal array:
[[1 2 3]
 [4 5 6]]
Transpoe array:
[[1 4]
 [2 5]
 [3 6]]
